sudo: required
dist: trusty

install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-1.0.0-preview2.1-003177 -y
  - dotnet restore ./src
  - dotnet restore ./tests
  - dotnet build ./tests/PrimeService.Tests
script:
  - dotnet test ./tests/PrimeService.Tests
